// Regenerate the world-city gazetteer for the Upplevelser map. NOT run at build
// time — the output (src/lib/cityData.js) is committed. To regenerate:
//   npm i -D all-the-cities && node scripts/gen-cities.mjs && npm remove all-the-cities
//
// Cities with population > THRESHOLD, plus every national/admin capital, plus a
// curated list of small-but-famous travel spots. Deduped by normalised name,
// highest population wins. Output format per line: Name|lng|lat
import cities from 'all-the-cities'
import { writeFileSync } from 'node:fs'

const THRESHOLD = 15000

const norm = (s) => s.normalize('NFD').replace(/[̀-ͯ]/g, '').toLowerCase().replace(/\s+/g, ' ').trim()

const FAMOUS = [ // small places people actually travel to
  'Ayia Napa','Zanzibar','Santorini','Mykonos','Positano','Chamonix','Zermatt','Interlaken',
  'Hallstatt','Cinque Terre','Dubrovnik','Kotor','Mostar','Banff','Queenstown','Cusco',
  'Siem Reap','Hoi An','Luang Prabang','Ubud','Cappadocia','Petra','Sharm el-Sheikh',
  'Reine','Åre','Riksgränsen','Abisko','Nusfjord','Positano','Taghazout','Essaouira',
]

const byName = new Map()
const add = (name, cc, lng, lat, pop) => {
  const k = norm(name)
  if (!k) return
  const prev = byName.get(k)
  if (!prev || pop > prev.pop) byName.set(k, { name, cc, lng: +lng.toFixed(2), lat: +lat.toFixed(2), pop })
}

for (const c of cities) {
  const isCapital = c.featureCode === 'PPLC' || c.featureCode === 'PPLA'
  if (c.population > THRESHOLD || isCapital) {
    const [lng, lat] = c.loc.coordinates
    add(c.name, c.country, lng, lat, c.population + (isCapital ? 5_000_000 : 0))
  }
}
// famous small spots — force-include even if tiny
const famousNorm = new Set(FAMOUS.map(norm))
for (const c of cities) {
  if (famousNorm.has(norm(c.name)) && !byName.has(norm(c.name))) {
    const [lng, lat] = c.loc.coordinates
    add(c.name, c.country, lng, lat, c.population)
  }
}

const rows = [...byName.values()].sort((a, b) => a.name.localeCompare(b.name))
// One row per normalised name (most-populous instance globally). Format: Name|lng|lat
const str = rows.map(r => `${r.name}|${r.lng}|${r.lat}`).join('\n')

const out = `// AUTO-GENERATED by scripts/gen-cities.mjs — do not edit. Regenerate with:
//   node scripts/gen-cities.mjs   (needs the all-the-cities devDependency)
// ${rows.length} cities: population > ${THRESHOLD} + every national/admin capital
// + a curated set of small famous travel spots. Format per line: Name|lng|lat
export const CITY_DATA = ${JSON.stringify(str)}
`
writeFileSync(new URL('../src/lib/cityData.js', import.meta.url), out)
console.log(`wrote ${rows.length} cities, ${(str.length / 1024).toFixed(0)} KB raw`)
