-- post_deploy_26 — condensed profile for Jarvis.
--
-- about_me (the user's own text, can be ~40k chars) stays untouched and is
-- still what Jarvis reads via fetch_memory_goals. about_me_summary is the
-- condensed version sent with EVERY Jarvis request (generated by the app via
-- src/lib/profileSummary.js, editable in Settings).
alter table public.user_settings
  add column if not exists about_me_summary text,
  add column if not exists about_me_summary_at timestamptz;
